version: "3.9"
services:
  data-biblia-chat:
    image: data-biblia-chat
    networks:
      - redmasiva
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels: # Labels moved under deploy
        - "traefik.enable=true"
        - "traefik.http.routers.data-biblia-chat.rule=Host(`data.biblia.chat`)"
        - "traefik.http.routers.data-biblia-chat.entrypoints=websecure"
        - "traefik.http.routers.data-biblia-chat.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.data-biblia-chat.priority=1"
        - "traefik.http.routers.data-biblia-chat.service=data-biblia-chat"
        - "traefik.http.services.data-biblia-chat.loadbalancer.server.port=1020"
        - "traefik.http.services.data-biblia-chat.loadbalancer.passHostHeader=true"
networks:
  redmasiva:
    external: true
    name: redmasiva